api/routes/reports.py:974: trailing whitespace.
[32m+[m[41m      [m
app/schemas/report.py:11: trailing whitespace.
[32m+[m[41m    [m
app/services/chart_generator.py:69: trailing whitespace.
[32m+[m[41m            [m
app/services/chart_generator.py:70: trailing whitespace.
[32m+[m[41m     [m
app/services/excel_reader.py:125: trailing whitespace.
[32m+[m[41m   [m
app/services/excel_reader.py:360: trailing whitespace.
[32m+[m[41m        [m
app/services/excel_reader.py:396: trailing whitespace.
[32m+[m[32m    return tables[m[41m   [m
app/services/report_style.py:21: trailing whitespace.
[32m+[m[41m    [m
app/services/result_analyzer.py:118: trailing whitespace.
[32m+[m[41m        [m
app/services/title_page.py:16: trailing whitespace.
[32m+[m[32m    3965,[m[41m  [m
app/services/title_page.py:17: trailing whitespace.
[32m+[m[32m    1702,[m[41m  [m
app/services/title_page.py:18: trailing whitespace.
[32m+[m[32m    1981,[m[41m  [m
app/services/title_page.py:19: trailing whitespace.
[32m+[m[32m    1416,[m[41m  [m
tests/test_reports_api.py:481: trailing whitespace.
[32m+[m[41m    [m
tests/test_reports_api.py:482: trailing whitespace.
[32m+[m[41m    [m
tests/test_reports_api.py:763: trailing whitespace.
[32m+[m[41m    [m
tests/test_reports_api.py:977: trailing whitespace.
[32m+[m[41m    [m
tests/test_reports_api.py:978: trailing whitespace.
[32m+[m[41m    [m
tests/test_reports_api.py:1106: trailing whitespace.
[32m+[m[41m    [m
tests/test_reports_api.py:1107: trailing whitespace.
[32m+[m[41m    [m
